version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=techsolutio
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tecnolosutio?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "12345678",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "techsolutio.app.jwtCookieName" : "techsolutio",
        "techsolutio.app.jwtSecret" : "======================Techsolutio=Spring===========================",
        "techsolutio.app.jwtExpirationMs" : "30000",
        "spring.jpa.defer-datasource-initialization" : "true",
        "spring.sql.init.mode" : "always"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: